export enum Permission {
  // User management
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',

  // Tenant
  TENANT_CREATE = 'TENANT_CREATE',
  TENANT_VIEW = 'TENANT_VIEW',
  TENANT_STATUS_CHANGE = 'TENANT_STATUS_CHANGE',

  //Customer management
  CUSTOMER_CREATE = 'CUSTOMER_CREATE',
  CUSTOMER_VIEW = 'CUSTOMER_VIEW',
  CUSTOMER_UPDATE = 'CUSTOMER_UPDATE',
  CUSTOMER_DELETE = 'CUSTOMER_DELETE',
  CUSTOMER_RESTORE = 'CUSTOMER_RESTORE',
}
